# parameter.py

# saving path
FOLDER_NAME = 'pred7'
model_path = f'checkpoints/{FOLDER_NAME}'
train_path = f'{model_path}/train'
gifs_path = f'{model_path}/gifs'

# predictor settings
generator_path = f'checkpoints/wgan_3000'
N_GEN_SAMPLE = 4
N_AGENTS = 3

# save training data
SUMMARY_WINDOW = 32
LOAD_MODEL = False
SAVE_IMG_GAP = 500

# map / planning resolution
CELL_SIZE = 0.4
NODE_RESOLUTION = 4
FRONTIER_CELL_SIZE = 2 * CELL_SIZE

# map representation
FREE = 255
OCCUPIED = 1
UNKNOWN = 127

# sensor / utility
SENSOR_RANGE = 16
UTILITY_RANGE = 0.8 * SENSOR_RANGE
MIN_UTILITY = 1

# updating map range
UPDATING_MAP_SIZE = 4 * SENSOR_RANGE + 4 * NODE_RESOLUTION

# training
MAX_EPISODE_STEP = 128
REPLAY_SIZE = 10000
MINIMUM_BUFFER_SIZE = 2000
BATCH_SIZE = 64
LR = 1e-5
GAMMA = 1
NUM_META_AGENT = 18

# network
NODE_INPUT_DIM = 9
EMBEDDING_DIM = 128

# graph
K_SIZE = 25
NODE_PADDING_SIZE = 960

# GPU
USE_GPU = True
USE_GPU_GLOBAL = True
NUM_GPU = 3

USE_WANDB = False

# comms / motion cost
COMMS_RANGE = 32.0
MAX_TRAVEL_COEF = 0
TOTAL_TRAVEL_COEF = 0

INTENT_HORIZON = 3

RDV_VERBOSE = True

RDV_CAND_UPDATE_EVERY = 6     
RDV_CAND_K = 400             
RDV_TOP_M = 40
RDV_CAND_STRIDE = 3          
RDV_TAU_FREE = 0.60          

RDV_INFO_RADIUS_M = 8.0
RDV_ALPHA = 1.0
RDV_BETA  = 0.5
RDV_GAMMA = 0.2

RDV_WINDOW_ALPHA_EARLY = 0.30
RDV_WINDOW_BETA_EARLY  = 6.0
RDV_WINDOW_ALPHA_LATE  = 0.40
RDV_WINDOW_BETA_LATE   = 8.0

RDV_REGION_FRAC = 0.45   # r = frac * COMMS_RANGE

RDV_BACKUP_MIN_DIST = 10.0   # meters

RDV_TT_N_SAMPLES = 16
RDV_EPSILON = 0.15   

RDV_PLAN_REPLAN_EVERY = 2
RDV_COSTMAP_UPDATE_EVERY = 4
RDV_DSTAR_MAX_EXPAND = 20000

RDV_RISK_LAMBDA = 0.6    
RDV_INFO_EPS    = 0.05   
RDV_ALLOW_UNKNOWN_IN_DSTAR = False